apiVersion: v1
kind: Pod
metadata:
  name: myapp10
  labels:
    type: MyApp10
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp20
  labels:
    type: MyApp10
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
spec:
  selector:
    type: MyApp10
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Powershell machine
apiVersion: v1
kind: Pod
metadata:
  name: pstest
spec:
  containers:
  - name: powershell
    image: mcr.microsoft.com/powershell